/*
 * Base d'aliments (valeurs pour 100 g / 100 ml, ordre de grandeur type Ciqual).
 *
 * Champs :
 *   n  : nom affiché
 *   k  : kcal pour 100 g
 *   p  : protéines (g) pour 100 g
 *   u  : poids en g d'« une » unité  ("2 oeufs" -> 2 x u)
 *   s  : portion par défaut en g quand aucune quantité n'est donnée
 *   po : poids des portions particulières à cet aliment (tranche, cas, bol...)
 *   a  : alias / façons de l'écrire
 *   l  : true si liquide (1 ml ~ 1 g)
 */
const FOODS = [
  // ---------------------------------------------------------------- viandes
  { n: "Blanc de poulet", k: 165, p: 31, u: 120, a: ["poulet", "blanc de poulet", "filet de poulet", "escalope de poulet", "poulet grille", "poulet roti", "aiguillettes de poulet"] },
  { n: "Cuisse de poulet", k: 190, p: 26, u: 130, a: ["cuisse de poulet", "pilon de poulet", "haut de cuisse"] },
  { n: "Escalope de dinde", k: 135, p: 29, u: 120, a: ["dinde", "escalope de dinde", "blanc de dinde", "filet de dinde"] },
  { n: "Steak haché 5%", k: 137, p: 21, u: 100, a: ["steak hache 5", "steak hache", "viande hachee 5", "hache 5", "boeuf hache 5"] },
  { n: "Steak haché 15%", k: 220, p: 19, u: 100, a: ["steak hache 15", "viande hachee 15", "hache 15"] },
  { n: "Steak haché 20%", k: 250, p: 18, u: 100, a: ["steak hache 20", "viande hachee", "viande hachee 20", "hache 20"] },
  { n: "Steak de bœuf", k: 160, p: 26, u: 150, a: ["steak", "boeuf", "bavette", "rumsteck", "faux filet", "steak de boeuf"] },
  { n: "Entrecôte", k: 250, p: 26, u: 200, a: ["entrecote", "cote de boeuf", "ribeye"] },
  { n: "Rôti de bœuf", k: 150, p: 28, u: 120, a: ["roti de boeuf", "rosbif"] },
  { n: "Veau", k: 160, p: 28, u: 150, a: ["veau", "escalope de veau"] },
  { n: "Côte de porc", k: 210, p: 25, u: 150, a: ["porc", "cote de porc", "echine de porc"] },
  { n: "Filet mignon de porc", k: 145, p: 28, u: 130, a: ["filet mignon", "filet mignon de porc"] },
  { n: "Agneau", k: 240, p: 25, u: 150, a: ["agneau", "cotelette d agneau", "gigot"] },
  { n: "Magret de canard", k: 200, p: 22, u: 180, a: ["canard", "magret", "magret de canard"] },
  { n: "Jambon blanc", k: 110, p: 20, u: 40, po: { tranche: 40 }, a: ["jambon", "jambon blanc", "jambon de paris", "tranche de jambon"] },
  { n: "Jambon cru", k: 240, p: 27, u: 25, po: { tranche: 25 }, a: ["jambon cru", "jambon serrano", "prosciutto", "jambon de bayonne"] },
  { n: "Bacon", k: 320, p: 25, u: 15, po: { tranche: 15 }, a: ["bacon", "poitrine fumee"] },
  { n: "Lardons", k: 290, p: 15, s: 60, a: ["lardons", "lardon"] },
  { n: "Saucisse", k: 300, p: 14, u: 70, a: ["saucisse", "chipolata", "saucisse de toulouse", "knacki", "saucisse de strasbourg"] },
  { n: "Merguez", k: 320, p: 15, u: 70, a: ["merguez"] },
  { n: "Chorizo", k: 450, p: 24, u: 8, po: { tranche: 8 }, a: ["chorizo"] },
  { n: "Saucisson", k: 420, p: 25, u: 8, po: { tranche: 8 }, a: ["saucisson", "saucisson sec", "rosette"] },
  { n: "Boudin noir", k: 380, p: 14, u: 120, a: ["boudin", "boudin noir"] },
  { n: "Foie gras", k: 460, p: 9, u: 40, po: { tranche: 40 }, a: ["foie gras"] },
  { n: "Nuggets de poulet", k: 290, p: 15, u: 20, a: ["nuggets", "nugget", "mcnuggets", "chicken nuggets"] },
  { n: "Cordon bleu", k: 250, p: 16, u: 100, a: ["cordon bleu"] },

  // --------------------------------------------------------------- poissons
  { n: "Saumon", k: 200, p: 20, u: 130, po: { pave: 130 }, a: ["saumon", "pave de saumon", "filet de saumon"] },
  { n: "Saumon fumé", k: 180, p: 22, u: 25, po: { tranche: 25 }, a: ["saumon fume"] },
  { n: "Thon au naturel", k: 110, p: 26, u: 110, po: { boite: 110 }, a: ["thon", "thon nature", "thon au naturel", "boite de thon"] },
  { n: "Thon à l'huile", k: 190, p: 24, u: 110, po: { boite: 110 }, a: ["thon a l huile", "thon huile"] },
  { n: "Cabillaud", k: 80, p: 18, u: 130, a: ["cabillaud", "morue", "dos de cabillaud"] },
  { n: "Colin / lieu", k: 80, p: 18, u: 130, a: ["colin", "lieu", "merlu", "filet de poisson blanc"] },
  { n: "Truite", k: 120, p: 20, u: 130, a: ["truite"] },
  { n: "Dorade / bar", k: 100, p: 20, u: 150, a: ["dorade", "bar", "loup"] },
  { n: "Sardines à l'huile", k: 220, p: 25, u: 95, po: { boite: 95 }, a: ["sardine", "sardines", "boite de sardines"] },
  { n: "Maquereau", k: 200, p: 19, u: 110, a: ["maquereau", "maquereaux"] },
  { n: "Crevettes", k: 100, p: 22, s: 120, u: 8, a: ["crevette", "crevettes", "gambas"] },
  { n: "Moules", k: 90, p: 12, s: 250, a: ["moule", "moules"] },
  { n: "Calamar", k: 90, p: 16, s: 120, a: ["calamar", "calamars", "encornet"] },
  { n: "Surimi", k: 100, p: 8, u: 17, a: ["surimi", "batonnet de surimi"] },
  { n: "Poisson pané", k: 200, p: 12, u: 60, a: ["poisson pane", "croque poisson", "fish stick"] },

  // ------------------------------------------------------------------ œufs
  { n: "Œuf", k: 145, p: 13, u: 55, a: ["oeuf", "oeufs", "oeuf dur", "oeuf au plat", "oeuf brouille", "oeuf a la coque", "oeuf poche"] },
  { n: "Blanc d'œuf", k: 48, p: 11, u: 33, a: ["blanc d oeuf", "blancs d oeuf", "blanc d oeufs"] },
  { n: "Jaune d'œuf", k: 320, p: 16, u: 18, a: ["jaune d oeuf", "jaunes d oeuf"] },
  { n: "Omelette", k: 155, p: 11, s: 150, a: ["omelette"] },

  // --------------------------------------------------------------- végétal
  { n: "Tofu", k: 120, p: 12, s: 100, a: ["tofu", "tofu nature"] },
  { n: "Tofu fumé", k: 150, p: 16, s: 100, a: ["tofu fume"] },
  { n: "Seitan", k: 140, p: 25, s: 100, a: ["seitan"] },
  { n: "Steak végétal", k: 180, p: 17, u: 100, a: ["steak vegetal", "galette vegetale", "steak de soja"] },
  { n: "Whey / protéine en poudre", k: 380, p: 78, s: 30, po: { dose: 30, scoop: 30, cas: 15 }, a: ["whey", "proteine", "proteine en poudre", "shaker de whey", "dose de whey"] },

  // ------------------------------------------------------------- féculents
  { n: "Riz cuit", k: 130, p: 2.7, s: 200, po: { bol: 200, assiette: 220 }, a: ["riz", "riz blanc", "riz cuit", "riz basmati", "riz thai"] },
  { n: "Riz cru (pesé sec)", k: 350, p: 7, s: 80, a: ["riz cru", "riz sec", "riz pese cru"] },
  { n: "Riz complet cuit", k: 120, p: 2.6, s: 200, a: ["riz complet", "riz brun"] },
  { n: "Pâtes cuites", k: 158, p: 5.5, s: 200, po: { assiette: 250, bol: 220 }, a: ["pates", "pate", "spaghetti", "penne", "fusilli", "tagliatelles", "coquillettes", "macaroni", "pates cuites"] },
  { n: "Pâtes crues (pesées sèches)", k: 360, p: 12, s: 80, a: ["pates crues", "pates seches", "pates pesees crues"] },
  { n: "Semoule cuite", k: 120, p: 4, s: 200, a: ["semoule", "semoule de ble"] },
  { n: "Couscous cuit", k: 115, p: 3.8, s: 200, a: ["couscous", "graine de couscous"] },
  { n: "Boulgour cuit", k: 110, p: 3.8, s: 200, a: ["boulgour", "bulgur"] },
  { n: "Quinoa cuit", k: 120, p: 4.4, s: 200, a: ["quinoa"] },
  { n: "Pomme de terre", k: 85, p: 2, u: 150, s: 200, a: ["pomme de terre", "pommes de terre", "patate", "patates", "pdt"] },
  { n: "Purée", k: 90, p: 2, s: 250, a: ["puree", "puree de pommes de terre"] },
  { n: "Frites", k: 300, p: 3.5, s: 130, po: { portion: 130, barquette: 130, cornet: 130 }, a: ["frite", "frites", "frites maison", "potatoes"] },
  { n: "Patate douce", k: 90, p: 1.6, u: 200, s: 200, a: ["patate douce", "patates douces"] },
  { n: "Baguette / pain", k: 270, p: 9, u: 250, po: { tranche: 30, morceau: 60, bout: 60 }, a: ["pain", "baguette", "pain blanc", "demi baguette", "ficelle"] },
  { n: "Pain complet", k: 250, p: 9, u: 250, po: { tranche: 35 }, a: ["pain complet", "pain aux cereales", "pain de campagne", "pain seigle"] },
  { n: "Pain de mie", k: 280, p: 8, u: 30, po: { tranche: 30 }, a: ["pain de mie", "toast", "toasts"] },
  { n: "Biscotte", k: 400, p: 11, u: 8, a: ["biscotte", "biscottes", "cracotte"] },
  { n: "Pain à burger", k: 280, p: 9, u: 60, a: ["pain a burger", "pain burger", "bun"] },
  { n: "Pain pita", k: 275, p: 9, u: 65, a: ["pita", "pain pita"] },
  { n: "Wrap / tortilla", k: 300, p: 8, u: 60, a: ["wrap", "tortilla", "galette de ble"] },
  { n: "Flocons d'avoine", k: 380, p: 13, s: 60, po: { cas: 10, bol: 60 }, a: ["flocons d avoine", "avoine", "porridge", "oatmeal"] },
  { n: "Muesli", k: 400, p: 10, s: 60, po: { bol: 60 }, a: ["muesli", "granola"] },
  { n: "Céréales", k: 380, p: 7, s: 40, po: { bol: 40 }, a: ["cereales", "corn flakes", "chocapic", "special k"] },
  { n: "Lentilles cuites", k: 115, p: 9, s: 200, a: ["lentille", "lentilles"] },
  { n: "Pois chiches cuits", k: 140, p: 8, s: 150, a: ["pois chiche", "pois chiches"] },
  { n: "Haricots rouges", k: 120, p: 8, s: 150, a: ["haricot rouge", "haricots rouges"] },
  { n: "Haricots blancs", k: 110, p: 7, s: 150, a: ["haricot blanc", "haricots blancs", "flageolets"] },
  { n: "Maïs", k: 100, p: 3, s: 100, a: ["mais", "mais doux"] },

  // -------------------------------------------------------------- laitages
  { n: "Lait entier", k: 65, p: 3.3, l: 1, s: 200, po: { verre: 200, bol: 250 }, a: ["lait entier"] },
  { n: "Lait demi-écrémé", k: 47, p: 3.3, l: 1, s: 200, po: { verre: 200, bol: 250 }, a: ["lait", "lait demi ecreme", "lait 1/2 ecreme"] },
  { n: "Lait écrémé", k: 35, p: 3.4, l: 1, s: 200, a: ["lait ecreme"] },
  { n: "Lait d'amande", k: 25, p: 0.5, l: 1, s: 200, a: ["lait d amande", "boisson amande"] },
  { n: "Lait de soja", k: 45, p: 3.3, l: 1, s: 200, a: ["lait de soja", "boisson soja"] },
  { n: "Yaourt nature", k: 60, p: 4, u: 125, po: { pot: 125 }, a: ["yaourt", "yaourt nature", "yogourt"] },
  { n: "Yaourt aux fruits", k: 90, p: 3.5, u: 125, po: { pot: 125 }, a: ["yaourt aux fruits", "yaourt sucre", "yaourt fruit"] },
  { n: "Yaourt grec", k: 115, p: 6, u: 150, po: { pot: 150 }, a: ["yaourt grec", "grec"] },
  { n: "Skyr", k: 60, p: 11, u: 150, po: { pot: 150 }, a: ["skyr"] },
  { n: "Fromage blanc 0%", k: 45, p: 8, s: 150, po: { pot: 100 }, a: ["fromage blanc 0", "fromage blanc 0%", "fromage blanc maigre"] },
  { n: "Fromage blanc 3%", k: 65, p: 7.5, s: 150, po: { pot: 100 }, a: ["fromage blanc", "fromage blanc 3", "fromage blanc nature"] },
  { n: "Petit suisse", k: 90, p: 8, u: 60, a: ["petit suisse", "petits suisses"] },
  { n: "Crème fraîche", k: 300, p: 2.5, s: 30, po: { cas: 15, cac: 5 }, a: ["creme fraiche", "creme epaisse"] },
  { n: "Crème liquide", k: 200, p: 2.5, l: 1, s: 30, po: { cas: 15 }, a: ["creme liquide", "creme entiere"] },
  { n: "Crème légère 15%", k: 165, p: 3, s: 30, po: { cas: 15 }, a: ["creme legere", "creme 15", "creme allegee"] },
  { n: "Beurre", k: 750, p: 0.7, s: 10, po: { cas: 10, cac: 5, noisette: 5, plaquette: 250 }, a: ["beurre"] },
  { n: "Emmental", k: 370, p: 28, s: 30, po: { tranche: 25, poignee: 30, cas: 8 }, a: ["emmental", "fromage rape", "gruyere rape", "fromage"] },
  { n: "Comté", k: 400, p: 28, s: 30, po: { tranche: 25 }, a: ["comte", "gruyere", "beaufort"] },
  { n: "Mozzarella", k: 250, p: 18, u: 125, po: { boule: 125 }, a: ["mozzarella", "mozza", "burrata"] },
  { n: "Chèvre", k: 300, p: 19, s: 30, a: ["chevre", "fromage de chevre", "buche de chevre"] },
  { n: "Camembert", k: 300, p: 20, u: 250, po: { part: 30, portion: 30 }, a: ["camembert", "brie", "coulommiers"] },
  { n: "Roquefort", k: 370, p: 19, s: 30, a: ["roquefort", "bleu", "gorgonzola"] },
  { n: "Feta", k: 265, p: 14, s: 40, a: ["feta"] },
  { n: "Parmesan", k: 400, p: 33, s: 15, po: { cas: 6 }, a: ["parmesan", "grana padano"] },
  { n: "Cheddar", k: 400, p: 25, s: 25, po: { tranche: 20 }, a: ["cheddar"] },
  { n: "Raclette", k: 350, p: 22, u: 30, po: { tranche: 30 }, a: ["raclette", "fromage a raclette"] },
  { n: "Vache qui rit", k: 260, p: 11, u: 17, a: ["vache qui rit", "fromage fondu"] },
  { n: "Kiri", k: 290, p: 8, u: 18, a: ["kiri", "philadelphia", "saint moret"] },
  { n: "Babybel", k: 320, p: 23, u: 20, a: ["babybel"] },
  { n: "Ricotta", k: 145, p: 11, s: 50, a: ["ricotta"] },
  { n: "Cottage cheese", k: 100, p: 12, s: 100, a: ["cottage cheese", "fromage cottage"] },

  // ---------------------------------------------------------------- fruits
  { n: "Pomme", k: 52, p: 0.3, u: 180, a: ["pomme", "pommes"] },
  { n: "Banane", k: 90, p: 1.1, u: 120, a: ["banane", "bananes"] },
  { n: "Orange", k: 47, p: 0.9, u: 180, a: ["orange", "oranges"] },
  { n: "Clémentine", k: 47, p: 0.8, u: 70, a: ["clementine", "clementines", "mandarine"] },
  { n: "Poire", k: 57, p: 0.4, u: 170, a: ["poire", "poires"] },
  { n: "Pêche / nectarine", k: 40, p: 0.9, u: 150, a: ["peche", "peches", "nectarine", "brugnon"] },
  { n: "Abricot", k: 48, p: 0.9, u: 50, a: ["abricot", "abricots"] },
  { n: "Raisin", k: 70, p: 0.6, s: 120, po: { poignee: 80, grappe: 150 }, a: ["raisin", "raisins"] },
  { n: "Fraises", k: 33, p: 0.7, s: 150, a: ["fraise", "fraises"] },
  { n: "Framboises", k: 52, p: 1.2, s: 125, a: ["framboise", "framboises"] },
  { n: "Myrtilles", k: 57, p: 0.7, s: 125, a: ["myrtille", "myrtilles"] },
  { n: "Cerises", k: 63, p: 1, s: 150, a: ["cerise", "cerises"] },
  { n: "Ananas", k: 50, p: 0.5, s: 150, po: { tranche: 80 }, a: ["ananas"] },
  { n: "Mangue", k: 60, p: 0.8, u: 250, a: ["mangue"] },
  { n: "Kiwi", k: 60, p: 1.1, u: 90, a: ["kiwi", "kiwis"] },
  { n: "Melon", k: 34, p: 0.8, s: 200, po: { part: 150, tranche: 150 }, a: ["melon"] },
  { n: "Pastèque", k: 30, p: 0.6, s: 250, po: { part: 200, tranche: 200 }, a: ["pasteque"] },
  { n: "Avocat", k: 160, p: 2, u: 130, a: ["avocat", "avocats"] },
  { n: "Citron", k: 29, p: 1.1, u: 60, a: ["citron", "citron vert"] },
  { n: "Pruneau", k: 240, p: 2.2, u: 8, a: ["pruneau", "pruneaux"] },
  { n: "Datte", k: 280, p: 2.5, u: 8, a: ["datte", "dattes"] },
  { n: "Figue", k: 74, p: 0.8, u: 50, a: ["figue", "figues"] },
  { n: "Compote", k: 60, p: 0.4, u: 100, po: { gourde: 90, pot: 100 }, a: ["compote", "compote de pommes", "gourde de compote"] },
  { n: "Raisins secs", k: 300, p: 3, s: 30, po: { poignee: 30 }, a: ["raisin sec", "raisins secs"] },

  // -------------------------------------------------------------- légumes
  { n: "Salade verte", k: 15, p: 1.4, s: 80, po: { bol: 100, assiette: 120 }, a: ["salade", "salade verte", "laitue", "mache", "roquette"] },
  { n: "Tomate", k: 18, p: 0.9, u: 120, a: ["tomate", "tomates"] },
  { n: "Tomates cerises", k: 18, p: 0.9, u: 12, s: 100, a: ["tomate cerise", "tomates cerises"] },
  { n: "Concombre", k: 12, p: 0.6, u: 300, s: 100, a: ["concombre"] },
  { n: "Carotte", k: 35, p: 0.8, u: 100, s: 150, a: ["carotte", "carottes", "carottes rapees"] },
  { n: "Courgette", k: 17, p: 1.2, u: 250, s: 200, a: ["courgette", "courgettes"] },
  { n: "Aubergine", k: 22, p: 1, u: 300, s: 200, a: ["aubergine", "aubergines"] },
  { n: "Poivron", k: 26, p: 1, u: 150, s: 150, a: ["poivron", "poivrons"] },
  { n: "Brocoli", k: 30, p: 3, s: 150, a: ["brocoli", "brocolis"] },
  { n: "Chou-fleur", k: 25, p: 2, s: 150, a: ["chou fleur", "choux fleur"] },
  { n: "Haricots verts", k: 30, p: 1.8, s: 150, a: ["haricot vert", "haricots verts"] },
  { n: "Épinards", k: 25, p: 2.7, s: 150, a: ["epinard", "epinards"] },
  { n: "Petits pois", k: 80, p: 5.4, s: 150, a: ["petit pois", "petits pois"] },
  { n: "Champignons", k: 22, p: 2.5, s: 120, a: ["champignon", "champignons"] },
  { n: "Oignon", k: 40, p: 1.2, u: 110, s: 60, a: ["oignon", "oignons", "echalote"] },
  { n: "Ail", k: 130, p: 6, u: 4, po: { gousse: 4 }, a: ["ail", "gousse d ail"] },
  { n: "Poireau", k: 30, p: 1.5, u: 150, s: 150, a: ["poireau", "poireaux"] },
  { n: "Betterave", k: 45, p: 1.6, s: 120, a: ["betterave", "betteraves"] },
  { n: "Endive", k: 17, p: 1, u: 120, s: 150, a: ["endive", "endives"] },
  { n: "Asperges", k: 22, p: 2.2, s: 150, a: ["asperge", "asperges"] },
  { n: "Choux de Bruxelles", k: 40, p: 3.4, s: 150, a: ["choux de bruxelles", "chou de bruxelles"] },
  { n: "Courge / potiron", k: 26, p: 1, s: 200, a: ["courge", "potiron", "butternut", "citrouille"] },
  { n: "Ratatouille", k: 60, p: 1.3, s: 200, a: ["ratatouille", "poelee de legumes", "legumes"] },
  { n: "Soupe de légumes", k: 40, p: 1.2, l: 1, s: 300, po: { bol: 300, assiette: 300 }, a: ["soupe", "soupe de legumes", "veloute", "potage"] },
  { n: "Crudités", k: 30, p: 1, s: 150, a: ["crudites"] },
  { n: "Taboulé", k: 140, p: 3, s: 150, a: ["taboule"] },
  { n: "Coleslaw", k: 150, p: 1, s: 100, a: ["coleslaw", "salade de chou"] },

  // -------------------------------------------------- gras & oléagineux
  { n: "Huile d'olive", k: 900, p: 0, l: 1, s: 10, po: { cas: 10, cac: 5, filet: 5 }, a: ["huile", "huile d olive", "huile olive"] },
  { n: "Huile de tournesol / colza", k: 900, p: 0, l: 1, s: 10, po: { cas: 10, cac: 5 }, a: ["huile de tournesol", "huile de colza"] },
  { n: "Amandes", k: 600, p: 21, s: 30, u: 1.2, po: { poignee: 30 }, a: ["amande", "amandes"] },
  { n: "Noix", k: 650, p: 15, s: 30, u: 5, po: { poignee: 30 }, a: ["noix", "cerneaux de noix"] },
  { n: "Noisettes", k: 630, p: 15, s: 30, po: { poignee: 30 }, a: ["noisette", "noisettes"] },
  { n: "Noix de cajou", k: 570, p: 18, s: 30, po: { poignee: 30 }, a: ["cajou", "noix de cajou"] },
  { n: "Pistaches", k: 560, p: 20, s: 30, po: { poignee: 30 }, a: ["pistache", "pistaches"] },
  { n: "Cacahuètes", k: 570, p: 26, s: 30, po: { poignee: 30 }, a: ["cacahuete", "cacahuetes", "arachide"] },
  { n: "Beurre de cacahuète", k: 600, p: 25, s: 20, po: { cas: 16, cac: 6 }, a: ["beurre de cacahuete", "peanut butter", "puree de cacahuete"] },
  { n: "Purée d'amande", k: 620, p: 21, s: 20, po: { cas: 16 }, a: ["puree d amande", "beurre d amande"] },
  { n: "Graines de courge", k: 560, p: 30, s: 20, po: { cas: 10 }, a: ["graines de courge"] },
  { n: "Graines de chia", k: 490, p: 17, s: 15, po: { cas: 12 }, a: ["chia", "graines de chia"] },
  { n: "Graines de lin / tournesol", k: 550, p: 19, s: 15, po: { cas: 10 }, a: ["graines de lin", "graines de tournesol", "graines"] },
  { n: "Olives", k: 145, p: 1, u: 4, s: 40, a: ["olive", "olives"] },
  { n: "Noix de coco", k: 350, p: 3.3, s: 30, a: ["noix de coco", "coco rapee"] },

  // ------------------------------------------------------- sucré & snacks
  { n: "Chocolat noir", k: 550, p: 8, s: 30, u: 10, po: { carre: 10, tablette: 100 }, a: ["chocolat noir", "chocolat"] },
  { n: "Chocolat au lait", k: 540, p: 7, s: 30, u: 10, po: { carre: 10, tablette: 100 }, a: ["chocolat au lait", "chocolat blanc"] },
  { n: "Pâte à tartiner", k: 540, p: 6, s: 20, po: { cas: 20, cac: 7 }, a: ["nutella", "pate a tartiner"] },
  { n: "Biscuit", k: 480, p: 6, u: 12, a: ["biscuit", "biscuits", "petit beurre", "prince", "sable"] },
  { n: "Cookie", k: 480, p: 5, u: 40, a: ["cookie", "cookies"] },
  { n: "Speculoos", k: 500, p: 6, u: 6, a: ["speculoos", "spéculoos"] },
  { n: "Part de gâteau", k: 380, p: 5, u: 90, po: { part: 90 }, a: ["gateau", "part de gateau", "quatre quarts", "cake"] },
  { n: "Brownie", k: 450, p: 5, u: 60, a: ["brownie", "brownies"] },
  { n: "Croissant", k: 400, p: 8, u: 60, a: ["croissant", "croissants"] },
  { n: "Pain au chocolat", k: 420, p: 7, u: 70, a: ["pain au chocolat", "chocolatine", "viennoiserie"] },
  { n: "Brioche", k: 350, p: 8, u: 35, po: { tranche: 35 }, a: ["brioche", "chinois"] },
  { n: "Crêpe", k: 220, p: 6, u: 70, a: ["crepe", "crepes"] },
  { n: "Pancake", k: 230, p: 6, u: 50, a: ["pancake", "pancakes"] },
  { n: "Gaufre", k: 380, p: 6, u: 80, a: ["gaufre", "gaufres"] },
  { n: "Madeleine", k: 440, p: 6, u: 25, a: ["madeleine", "madeleines"] },
  { n: "Chips", k: 540, p: 6, s: 30, po: { poignee: 25, sachet: 150, paquet: 150 }, a: ["chips", "tuc", "curly"] },
  { n: "Pop-corn", k: 480, p: 9, s: 30, po: { bol: 30, sachet: 90 }, a: ["popcorn", "pop corn"] },
  { n: "Bonbons", k: 350, p: 3, s: 30, po: { poignee: 30, paquet: 100 }, a: ["bonbon", "bonbons", "haribo"] },
  { n: "Barre chocolatée", k: 480, p: 5, u: 45, a: ["barre chocolatee", "snickers", "twix", "kinder", "mars", "bounty"] },
  { n: "Barre de céréales", k: 400, p: 6, u: 25, a: ["barre de cereales", "barre cereale"] },
  { n: "Barre protéinée", k: 350, p: 30, u: 60, a: ["barre proteinee", "barre proteine"] },
  { n: "Miel", k: 320, p: 0.3, s: 20, po: { cas: 20, cac: 7 }, a: ["miel"] },
  { n: "Confiture", k: 260, p: 0.4, s: 20, po: { cas: 20, cac: 7 }, a: ["confiture", "gelee"] },
  { n: "Sucre", k: 400, p: 0, s: 5, u: 5, po: { cac: 4, cas: 12, morceau: 5, sucrette: 5 }, a: ["sucre", "sucre blanc"] },
  { n: "Sirop d'érable", k: 260, p: 0, s: 20, po: { cas: 20 }, a: ["sirop d erable", "sirop erable"] },
  { n: "Glace", k: 200, p: 3.5, s: 100, u: 60, po: { boule: 60, pot: 100 }, a: ["glace", "creme glacee", "sorbet", "magnum"] },
  { n: "Crème dessert", k: 120, p: 3, u: 125, po: { pot: 125 }, a: ["creme dessert", "danette", "liegeois", "flan"] },
  { n: "Mousse au chocolat", k: 220, p: 4, u: 100, po: { pot: 100 }, a: ["mousse au chocolat"] },
  { n: "Riz au lait", k: 130, p: 3, u: 130, po: { pot: 130 }, a: ["riz au lait", "semoule au lait"] },
  { n: "Tarte", k: 300, p: 4, u: 110, po: { part: 110 }, a: ["tarte", "tarte aux pommes", "part de tarte", "tarte au citron"] },
  { n: "Éclair / pâtisserie", k: 300, p: 5, u: 90, a: ["eclair", "patisserie", "religieuse", "chou a la creme"] },
  { n: "Donut", k: 420, p: 6, u: 60, a: ["donut", "donuts", "beignet"] },
  { n: "Muffin", k: 400, p: 6, u: 80, a: ["muffin", "muffins"] },
  { n: "Tiramisu", k: 250, p: 4, u: 120, po: { part: 120, pot: 100 }, a: ["tiramisu"] },
  { n: "Cheesecake", k: 320, p: 6, u: 110, po: { part: 110 }, a: ["cheesecake"] },

  // ------------------------------------------------------------------ plats
  { n: "Pizza", k: 260, p: 11, u: 400, po: { part: 125, tranche: 125 }, a: ["pizza", "pizzas", "margherita", "reine", "4 fromages"] },
  { n: "Burger", k: 250, p: 13, u: 220, a: ["burger", "hamburger"] },
  { n: "Cheeseburger", k: 260, p: 13, u: 115, a: ["cheeseburger", "cheese"] },
  { n: "Big Mac", k: 251, p: 12, u: 219, a: ["big mac", "bigmac"] },
  { n: "Royal cheese / double burger", k: 255, p: 14, u: 200, a: ["royal cheese", "double cheese", "royal bacon", "quarter pounder"] },
  { n: "McChicken", k: 250, p: 12, u: 170, a: ["mcchicken", "chicken burger", "filet de poulet burger"] },
  { n: "Filet-O-Fish", k: 250, p: 12, u: 140, a: ["filet o fish", "fish burger"] },
  { n: "Whopper", k: 240, p: 12, u: 270, a: ["whopper"] },
  { n: "Kebab", k: 220, p: 12, u: 350, a: ["kebab", "grec", "durum", "sandwich grec"] },
  { n: "French tacos", k: 250, p: 11, u: 450, a: ["tacos", "french tacos", "tacos francais"] },
  { n: "Sandwich jambon-beurre", k: 250, p: 10, u: 200, a: ["jambon beurre", "sandwich jambon beurre", "sandwich"] },
  { n: "Sandwich poulet crudités", k: 190, p: 10, u: 220, a: ["sandwich poulet", "sandwich poulet crudites", "club sandwich"] },
  { n: "Croque-monsieur", k: 280, p: 15, u: 180, a: ["croque monsieur", "croque", "croque madame"] },
  { n: "Quiche lorraine", k: 280, p: 10, u: 130, po: { part: 130 }, a: ["quiche", "quiche lorraine", "tarte salee"] },
  { n: "Lasagnes", k: 130, p: 8, s: 350, po: { part: 300, assiette: 350, barquette: 300 }, a: ["lasagne", "lasagnes"] },
  { n: "Hachis parmentier", k: 120, p: 7, s: 350, a: ["hachis parmentier", "parmentier"] },
  { n: "Gratin dauphinois", k: 150, p: 3.5, s: 250, a: ["gratin", "gratin dauphinois"] },
  { n: "Sushi", k: 145, p: 6, u: 30, a: ["sushi", "sushis", "nigiri"] },
  { n: "Maki", k: 130, p: 4, u: 20, a: ["maki", "makis"] },
  { n: "California roll", k: 160, p: 5, u: 25, a: ["california", "california roll", "spring roll"] },
  { n: "Nems", k: 220, p: 8, u: 45, a: ["nem", "nems", "rouleau de printemps"] },
  { n: "Samoussa", k: 250, p: 7, u: 40, a: ["samoussa", "samoussas"] },
  { n: "Riz cantonais", k: 150, p: 6, s: 300, a: ["riz cantonais", "riz saute"] },
  { n: "Nouilles sautées", k: 160, p: 5, s: 300, a: ["nouilles sautees", "nouilles", "yakisoba", "chow mein"] },
  { n: "Pad thaï", k: 180, p: 8, s: 350, a: ["pad thai"] },
  { n: "Curry de poulet", k: 130, p: 10, s: 350, a: ["curry", "curry de poulet", "poulet curry", "tikka masala"] },
  { n: "Chili con carne", k: 130, p: 9, s: 350, a: ["chili", "chili con carne"] },
  { n: "Couscous (plat)", k: 150, p: 8, s: 400, a: ["couscous royal", "plat de couscous"] },
  { n: "Paella", k: 145, p: 7, s: 350, a: ["paella"] },
  { n: "Tartiflette", k: 180, p: 7, s: 350, a: ["tartiflette"] },
  { n: "Bo bun", k: 130, p: 7, s: 400, a: ["bo bun", "bobun"] },
  { n: "Poke bowl", k: 130, p: 8, s: 400, a: ["poke bowl", "poke"] },
  { n: "Burrito", k: 200, p: 9, u: 300, a: ["burrito", "fajita", "quesadilla"] },
  { n: "Wrap poulet", k: 200, p: 10, u: 250, a: ["wrap poulet", "wrap au poulet"] },
  { n: "Salade César", k: 150, p: 9, s: 300, a: ["salade cesar", "cesar"] },
  { n: "Pâtes bolognaise", k: 130, p: 6, s: 350, po: { assiette: 350 }, a: ["pates bolognaise", "bolognaise", "spaghetti bolognaise"] },
  { n: "Pâtes carbonara", k: 180, p: 7, s: 350, po: { assiette: 350 }, a: ["carbonara", "pates carbonara"] },
  { n: "Gnocchi", k: 180, p: 4, s: 250, a: ["gnocchi", "gnocchis"] },
  { n: "Raviolis", k: 160, p: 6, s: 250, a: ["ravioli", "raviolis", "tortellini"] },
  { n: "Blanquette / bœuf mijoté", k: 130, p: 11, s: 300, a: ["blanquette", "boeuf bourguignon", "bourguignon", "navarin"] },
  { n: "Moussaka", k: 130, p: 6, s: 300, a: ["moussaka"] },
  { n: "Galette bretonne", k: 180, p: 7, u: 150, a: ["galette", "galette complete", "galette bretonne"] },

  // ---------------------------------------------------------------- sauces
  { n: "Ketchup", k: 100, p: 1, s: 15, po: { cas: 15, cac: 5, dosette: 12 }, a: ["ketchup"] },
  { n: "Mayonnaise", k: 700, p: 1, s: 15, po: { cas: 12, cac: 5, dosette: 12 }, a: ["mayonnaise", "mayo"] },
  { n: "Moutarde", k: 150, p: 6, s: 10, po: { cas: 15, cac: 5 }, a: ["moutarde"] },
  { n: "Sauce blanche", k: 400, p: 1, s: 30, po: { cas: 15 }, a: ["sauce blanche", "sauce algerienne", "sauce samourai", "sauce burger"] },
  { n: "Vinaigrette", k: 450, p: 0, s: 15, po: { cas: 12, cac: 5 }, a: ["vinaigrette", "sauce salade"] },
  { n: "Sauce tomate", k: 40, p: 1.5, s: 100, po: { cas: 15 }, a: ["sauce tomate", "coulis de tomate", "passata"] },
  { n: "Sauce soja", k: 60, p: 6, s: 15, po: { cas: 15, cac: 5 }, a: ["sauce soja", "soja"] },
  { n: "Pesto", k: 450, p: 5, s: 20, po: { cas: 15 }, a: ["pesto"] },

  // ------------------------------------------------------------- boissons
  { n: "Eau", k: 0, p: 0, l: 1, s: 250, po: { verre: 250, bouteille: 500 }, a: ["eau", "eau petillante", "eau gazeuse"] },
  { n: "Café", k: 2, p: 0, l: 1, s: 100, po: { tasse: 100, mug: 250 }, a: ["cafe", "expresso", "espresso", "cafe noir"] },
  { n: "Café au lait", k: 45, p: 2.5, l: 1, s: 200, po: { tasse: 150, mug: 250, bol: 300 }, a: ["cafe au lait", "cafe latte", "latte", "noisette"] },
  { n: "Cappuccino", k: 55, p: 3, l: 1, s: 200, po: { tasse: 200 }, a: ["cappuccino", "capuccino"] },
  { n: "Thé / infusion", k: 1, p: 0, l: 1, s: 250, po: { tasse: 250, mug: 250 }, a: ["the", "infusion", "tisane"] },
  { n: "Chocolat chaud", k: 90, p: 3, l: 1, s: 250, po: { tasse: 250, bol: 300 }, a: ["chocolat chaud", "cacao"] },
  { n: "Jus d'orange", k: 45, p: 0.7, l: 1, s: 200, po: { verre: 200, brique: 250 }, a: ["jus d orange", "jus orange", "oasis orange"] },
  { n: "Jus de fruits", k: 47, p: 0.3, l: 1, s: 200, po: { verre: 200 }, a: ["jus de fruits", "jus de pomme", "jus multifruits", "jus"] },
  { n: "Coca / soda", k: 42, p: 0, l: 1, s: 330, po: { canette: 330, verre: 250, bouteille: 500 }, a: ["coca", "coca cola", "soda", "pepsi", "fanta", "sprite", "oasis", "orangina"] },
  { n: "Coca zéro / light", k: 0.3, p: 0, l: 1, s: 330, po: { canette: 330, verre: 250, bouteille: 500 }, a: ["coca zero", "coca light", "zero", "soda light", "pepsi max"] },
  { n: "Ice tea", k: 30, p: 0, l: 1, s: 330, po: { canette: 330, verre: 250, bouteille: 500 }, a: ["ice tea", "the glace", "lipton ice tea"] },
  { n: "Sirop dilué", k: 25, p: 0, l: 1, s: 250, po: { verre: 250 }, a: ["sirop", "sirop de menthe", "grenadine"] },
  { n: "Red Bull / énergisante", k: 45, p: 0, l: 1, s: 250, po: { canette: 250 }, a: ["red bull", "redbull", "monster", "boisson energisante"] },
  { n: "Smoothie", k: 60, p: 1, l: 1, s: 250, po: { verre: 250 }, a: ["smoothie"] },
  { n: "Milkshake", k: 110, p: 3, l: 1, s: 300, a: ["milkshake", "milk shake"] },
  { n: "Bière", k: 43, p: 0.5, l: 1, s: 250, po: { demi: 250, pinte: 500, canette: 330, bouteille: 330, verre: 250 }, a: ["biere", "bieres", "blonde", "ipa"] },
  { n: "Vin rouge", k: 85, p: 0, l: 1, s: 125, po: { verre: 125, bouteille: 750 }, a: ["vin", "vin rouge", "rouge"] },
  { n: "Vin blanc / rosé", k: 82, p: 0, l: 1, s: 125, po: { verre: 125, bouteille: 750 }, a: ["vin blanc", "rose", "vin rose"] },
  { n: "Champagne", k: 80, p: 0, l: 1, s: 100, po: { coupe: 100, verre: 100 }, a: ["champagne", "cremant", "prosecco"] },
  { n: "Alcool fort", k: 240, p: 0, l: 1, s: 40, po: { shot: 40, verre: 40, dose: 40 }, a: ["whisky", "vodka", "rhum", "gin", "tequila", "alcool"] },
  { n: "Cocktail", k: 130, p: 0, l: 1, s: 250, po: { verre: 250 }, a: ["cocktail", "mojito", "spritz", "punch", "pina colada"] },
];

if (typeof module !== "undefined") module.exports = { FOODS };
